---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: debian-7.6
  run_list:
    - recipe[apt]

suites:
- name: vicnum13
  run_list:
  - recipe[vicnum]
  attributes:
    vicnum:
      version: vicnum13
- name: vicnum14
  run_list:
  - recipe[vicnum]
  attributes:
    vicnum:
      version: vicnum14
- name: vicnum15
  run_list:
  - recipe[vicnum]
  attributes:
    vicnum:
      version: vicnum15
