---
driver:
  name: docker
  binary: docker
  use_sudo: false

platforms:
  - name: ubuntu-12.04
  - name: debian-7

suites:
  - name: vicnum14
    run_list:
      - recipe[vicnum]
    attributes:
      vicnum:
        version: vicnum14
  - name: vicnum15
    run_list:
      - recipe[vicnum]
    attributes:
      vicnum:
        version: vicnum15
